apiVersion: v1
kind: Config
clusters:
  - name: "newrancher"
    cluster:
      server: "https://rancher.choicesaas.cn/k8s/clusters/local"
      certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQ\
      WYyZ0F3SUJBZ0lKQUlaRzluamRtNUYrTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ0V4Q3pBSkJnTlYKQ\
      kFZVEFrTk9NUkl3RUFZRFZRUUREQWxzYjJOaGJHaHZjM1F3SGhjTk1Ua3dOVEEyTURrME1UUXlXa\
      GNOTWprdwpOVEF6TURrME1UUXlXakFoTVFzd0NRWURWUVFHRXdKRFRqRVNNQkFHQTFVRUF3d0piR\
      zlqWVd4b2IzTjBNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5S\
      TNqaXlnanliWnpXbnhxbmZOZ20yTkoKTHVUU3B2T0EvMXJualpuMlQ3d3p4VHlYbFE0eGkvTVJsM\
      HlMcS9Lc3J5SlNCVHhoL1VLV2svSk1XS3Z4VFhTRQpzU0UwUE9sYSt2N1NESmYvRkh6SmJpNTBXN\
      DNGRWFnSUZLSHN0U1FLUnNVQkFSb21NQ0xpQ25BWUVzTFhianlTCldoUjBYOWRlMlNvZXdaRUV3W\
      ktIeHdnNHBxbGRSVzIrWEdpTnVsYlhXRGhRMElrL2JQNUxWMzdyaXcyS0M3Q0UKV1RkbWxKbmpYS\
      lluZzVrZUdxRDRSSEtKYTBjUGlQc2U4S3EyY1FNVGlMVjUwUUs5ZHU0OTJEa1JxSG14ejlMeAp6W\
      lhpT29zMlRQMXZvTDRmeWtBa2ZRa2RsWlN1aGMwWVU4L0F6TWEvNGplQVY3MlNQT1NGSHpPYnIvO\
      FJHUUlECkFRQUJvMUF3VGpBZEJnTlZIUTRFRmdRVTQ0NStzSDcvQkZGVDZrVWkvSGNiUkpnYXFzU\
      XdId1lEVlIwakJCZ3cKRm9BVTQ0NStzSDcvQkZGVDZrVWkvSGNiUkpnYXFzUXdEQVlEVlIwVEJBV\
      XdBd0VCL3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFJRE55RmIwMTBJSUFEZGsrN2tINnZya\
      m9PVmNlYy9hM29ZZzlKVisxQTlVN3FIRGp1akNnCkYwc2x0NElDcnZTK08rOXh1RTRNL1ltRHlHZ\
      mRYUU1lYTdYSUsvNU1ZMzNqRUJCUGpad1RMelQ5dzdwNklnOFUKSm10di93YmF6YTlNRG9pL1IxN\
      TJ4cm1Nc2VwVXBqWkwrTVk5bFd2RUtYbHpIbkMzSEdQSE5RUnZmWGJMeFYwLwpDQmlZVVZTVExwV\
      kpnSzM5UVVCZHZjNEdiQmJzcG5YUWNsQVRtekxHa0xQSHJ6bVRqQ09iNTUrTjc2MlFKTjViCi9jM\
      FcrQ3p4Y0FqN1NmR1BCb3R6YlJwQ3ZNeEFpc0x2MkVHS2l4RTNSdU51YThoZXZiTzhMUWtLR0VaT\
      3QvWHoKWFhXQTI4eE9TVExYMnBZMXZMUzRERy80SXp0ZElhcGgwZz09Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0="

users:
  - name: "newrancher"
    user:
      token: "kubeconfig-user-kkdrp:rnqgc2kd98q8tgg56rbq5k2dtkmtps5qj6dqldmjhnhq9swf4hdw47"

contexts:
  - name: "newrancher"
    context:
      user: "newrancher"
      cluster: "newrancher"

current-context: "newrancher"
